image: Visual Studio 2015
branches:
  except:
    - gh-pages

install:
  - set QTDIR=C:\Qt\5.11.2\mingw53_32
  - set PATH=C:\MinGW\bin;%QTDIR%/bin;;%PATH%

before_build:
  - cd app

build_script:
  # - sed -i "QMAKE_CXXFLAGS += -std=c++0x"/"QT += gui"/"QT += core"/"QT += widgets"/"QT += testlib"/"QT += xml"/"DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" PictureCrypt.pro
  # - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" PictureCrypt.pro
  # - qmake "QMAKE_CXXFLAGS += -std=c++0x" "QT += gui" "QT += core" "QT += widgets" "QT += testlib" "QT += xml" "DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" # -r -spec win32-g++
  - qmake.exe C:\projects\picturecrypt\app\PictureCrypt.pro -spec win32-g++ "CONFIG+=debug" && C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe qmake_all
  - mingw32-make.exe all
  - sh: sh ../scripts/clean.sh

  - mkdir deploy
  - cd deploy
  - mkdir PictureCrypt
  - mkdir tests

  - cd ../src
  - sh: sh ../scripts/clean.sh

  - cd ../tests
  - sh: sh ../scripts/clean.sh

  - cd ..
  - move src/src.exe deploy/PictureCrypt/PictureCrypt.exe
  - move tests/tests.exe deploy/tests/tests.exe

  - cd deploy/PictureCrypt
  - windeployqt.exe --release PictureCrypt.exe

  - cd ../tests
  - windeployqt.exe --release tests.exe

test_script:
  - ./tests.exe -xunitxml > tests.xml

on_finish:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./tests.xml))

artifacts:
  - path: app\deploy
    name: PictureCrypt

deploy:
  provider: S3
  access_key_id:
    secure: KROVK6x7RsvQ5v9onhcQ65toKcMpimgVKfA9SSVWEG8=
  secret_access_key:
    secure: aTO7A/REbTL5m27x2H72Gq7Lljf8WQ3EE6NWCVHtkTDvERvs99vePDyi6GkV2gVl
  bucket: waleko-acacia
  region: eu-west-1
  folder: appveyor
  artifact: PictureCrypt
