image: Visual Studio 2015
branches:
  except:
    - gh-pages

install:
  - set QTDIR=C:\Qt\5.11.2\mingw53_32
  - set PATH=C:\MinGW\bin;%QTDIR%/bin;;%PATH%
before_build:
  - cd app
  - mkdir deploy

build_script:
  # - sed -i "QMAKE_CXXFLAGS += -std=c++0x"/"QT += gui"/"QT += core"/"QT += widgets"/"QT += testlib"/"QT += xml"/"DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" PictureCrypt.pro
  # - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" PictureCrypt.pro
  # - qmake "QMAKE_CXXFLAGS += -std=c++0x" "QT += gui" "QT += core" "QT += widgets" "QT += testlib" "QT += xml" "DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" # -r -spec win32-g++
  - cd src
  - qmake.exe C:\projects\picturecrypt\app\src\src.pro -spec win32-g++ "CONFIG+=debug" && C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe all
  - mingw32-make.exe clean -j8
  - sh: sh ../scripts/clean.sh

  - cd ..
  - move src/build/Debug/PictureCrypt.exe deploy/PictureCrypt.exe
  - cd deploy
  - windeployqt.exe --release PictureCrypt.exe

before_test:
  - cd ../tests
  - qmake.exe C:\projects\picturecrypt\app\tests\tests.pro -spec win32-g++ "CONFIG+=debug"

test_script:
  - C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe check > ../tests.xml
  - cd ..

on_finish:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./tests.xml))

artifacts:
  - path: app\deploy
    name: PictureCrypt

deploy:
  provider: S3
  access_key_id:
    secure: KROVK6x7RsvQ5v9onhcQ65toKcMpimgVKfA9SSVWEG8=
  secret_access_key:
    secure: aTO7A/REbTL5m27x2H72Gq7Lljf8WQ3EE6NWCVHtkTDvERvs99vePDyi6GkV2gVl
  bucket: waleko-acacia
  region: eu-west-1
  folder: appveyor
  artifact: PictureCrypt
