language: cpp
compiler: gcc
dist: xenial
sudo: required
os:
  - linux
#  - windows

branches:
  except:
    - gh-pages

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

install:
  - cd app
  - sh ./scripts/install.sh
    # Setup qt
  - source /opt/qt511/bin/qt511-env.sh
  - export QTHOME=/opt/qt511

#before_script:
#  - cd src
script:
  - sh scripts/build.sh
  - sh scripts/test.sh
#  - 
#  - bash ./scripts/clean.sh

before_deploy:
  - cd src/doxy
  - sh ../../scripts/deploy.sh
#  - cd ../..
#  - pip install --user awscli
#  - aws s3 sync s3://mxe-qt/ mxe --region us-west-1 > s3.log
#  - cd src
#  - sh ./../scripts/deploy_windows.sh

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
#  - provider: s3
#    access_key_id: $AWS_ACCESS_KEY_ID
#    secret_access_key: $AWS_SECRET_ACCESS_KEY
#    bucket: waleko-cedar
#    skip_cleanup: true
#    region: us-west-1
