language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt57base
  - sudo apt-get install qtbase5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools qt5-qmake make

install:
  # C++14
  - sudo apt-get install g++-6
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - cd src
  - qmake -qt=qt5 "QMAKE_CXXFLAGS += -std=c++0x" "QT += gui" "QT += core" "QT += widgets" "DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900"
  - make
  - ./PictureCrypt
