language: cpp
compiler: gcc

std:
  - gnu++0x
  - c++0x
  - c++14
  - gnu++14
  - c++11
  - gnu++11

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools

install:
  # C++14
  - sudo apt-get install -qq g++-5
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - cd src
  - qmake
  - make -std=c++11
  - ./PictureCrypt
